## 2. Задание

### 2.1. Репозиторий на GitHub

1. Создать **публичный** репозиторий на GitHub на основе шаблона `aie-student-template`:
   - зайти на страницу шаблона;
   - нажать кнопку «Use this template»;
   - выбрать создание нового репозитория в своём аккаунте;
   - задать осмысленное имя репозитория (по инструкции курса).
2. Убедиться, что репозиторий создан и доступен по публичной ссылке.

### 2.2. Локальная настройка Git

1. Клонировать созданный репозиторий к себе на компьютер.
2. При необходимости настроить Git (имя и e-mail пользователя).
3. Убедиться, что команды `git status` и `git log` работают и показывают состояние репозитория.

### 2.3. Структура для HW01

1. В корне репозитория создать папку `homeworks/`, если её ещё нет.
2. Внутри `homeworks/` создать папку `HW01/`.
3. В папке `homeworks/HW01/` создать файл `HW01.ipynb` (или другой ноутбук с таким именем) с кодом по NumPy.

> Подробные рекомендации по ноутбукам см. в `guides/jupyter-101.md`.


Мой репозиторий: https://github.com/MyatnyjChaj3/AI_kurs_gr2.git


### 2.4. Содержание файла с NumPy

В файле `HW01.ipynb` должны быть:

1. Импорт библиотеки NumPy с общепринятым сокращением (`import numpy as np`).
2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.
3. Демонстрация атрибутов:
   - вывод формы (`shape`) и типа данных (`dtype`) для одного из массивов.
4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.
5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

Желательно добавить несколько комментариев в коде, кратко поясняющих, что делает каждая операция.

In [85]:
# 2.1
import numpy as np
import random
from math import *

In [86]:
quantity = random.randint(7, 11)
list_num1 = [i for i in range(quantity)]
list_num2 = [round(pow(i, e), 2) for i in range(quantity)]


In [87]:
# 2.2
a_nums = np.array([list_num1, list_num2])
a_zeros = np.zeros((6, 9))
a_ones = np.zeros((2, 2, 8))
a_one_matrix = np.eye(8)
a_step_matrix = np.arange(10, 1, -1)

In [88]:
# 2.3
a_nums.shape

(2, 11)

In [89]:
type(a_nums)

numpy.ndarray

In [90]:
# 2.4
print(a_step_matrix[4])
print(a_nums[:, 2:6])
print(a_nums[:, ::-1])
print(a_nums[:, 1::2])
print(a_nums[1])
print(a_nums[0, 4])

6
[[ 2.    3.    4.    5.  ]
 [ 6.58 19.81 43.31 79.43]]
[[ 10.     9.     8.     7.     6.     5.     4.     3.     2.     1.
    0.  ]
 [522.74 392.55 285.01 198.25 130.39  79.43  43.31  19.81   6.58   1.
    0.  ]]
[[  1.     3.     5.     7.     9.  ]
 [  1.    19.81  79.43 198.25 392.55]]
[  0.     1.     6.58  19.81  43.31  79.43 130.39 198.25 285.01 392.55
 522.74]
4.0


In [91]:
# 2.5
a1 = np.array(list_num1)
a2 = np.arange(quantity, 0, -1)
a12 = np.array([a1, a2])


square_difference = a1**2 - 2*a1*a2 + a2**2   #квадрат разности
powers = np.where(a1 % 2 == 0, a1 ** e, a1)   # где чётные → i^e, иначе оставляем i
trans_a12 = a12.T #транспонирование
multi_matrix = a1@a2.T #произведение матриц



In [92]:
print(a1, a2, a12, square_difference, powers.round(2), trans_a12, multi_matrix, sep="\n")


[ 0  1  2  3  4  5  6  7  8  9 10]
[11 10  9  8  7  6  5  4  3  2  1]
[[ 0  1  2  3  4  5  6  7  8  9 10]
 [11 10  9  8  7  6  5  4  3  2  1]]
[121  81  49  25   9   1   1   9  25  49  81]
[  0.     1.     6.58   3.    43.31   5.   130.39   7.   285.01   9.
 522.74]
[[ 0 11]
 [ 1 10]
 [ 2  9]
 [ 3  8]
 [ 4  7]
 [ 5  6]
 [ 6  5]
 [ 7  4]
 [ 8  3]
 [ 9  2]
 [10  1]]
220


In [93]:
print("\nСтатистики по powers:")
print("среднее =", powers.mean())
print("медиана =", np.median(powers))
print("стд. отклонение =", powers.std().round(3))
print("сумма =", powers.sum())
print("мин / макс =", powers.min(), "/", powers.max())


Статистики по powers:
среднее = 92.09242613497301
медиана = 7.0
стд. отклонение = 159.623
сумма = 1013.0166874847031
мин / макс = 0.0 / 522.7352996704365
